import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
} from 'react-native';
import { loadBackstories, buildCharacterModifier } from '../../game/CareerProgression';
import type { BackstoryId, CharacterProfile } from '../../game/CareerProgression';
import type { SaveStore } from '../../game/SaveStore';
import { colors } from '../theme';

interface Props {
  saveStore: SaveStore;
  /**
   * The per-save root RNG seed (#96), generated by the composition root for
   * this new game. Persisted here alongside the character so a reload
   * reproduces the same world; seed-generation policy stays in App.
   */
  masterSeed: number;
  onComplete: (profile: CharacterProfile) => void;
}

export function CharacterCreation({ saveStore, masterSeed, onComplete }: Props) {
  const backstories = loadBackstories();
  const [name, setName] = useState('');
  const [selectedId, setSelectedId] = useState<BackstoryId | null>(null);
  const [error, setError] = useState('');

  async function handleConfirm() {
    const trimmed = name.trim();
    if (!trimmed) {
      setError('Enter your name to continue.');
      return;
    }
    if (!selectedId) {
      setError('Choose a backstory to continue.');
      return;
    }
    const profile = buildCharacterModifier(trimmed, selectedId) as CharacterProfile;
    const existing = await saveStore.load();
    await saveStore.save({ ...(existing ?? {}), character: profile, masterSeed });
    onComplete(profile);
  }

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.heading}>Who are you?</Text>

      <TextInput
        style={styles.nameInput}
        placeholder="Your name"
        value={name}
        onChangeText={(v) => { setName(v); setError(''); }}
        maxLength={40}
      />

      <Text style={styles.subheading}>Choose your backstory</Text>

      {backstories.map((b) => {
        const active = selectedId === b.id;
        return (
          <TouchableOpacity
            key={b.id}
            style={[styles.backstoryCard, active && styles.backstoryCardActive]}
            onPress={() => { setSelectedId(b.id); setError(''); }}
            accessibilityRole="radio"
            accessibilityState={{ selected: active }}
          >
            <Text style={[styles.backstoryLabel, active && styles.backstoryLabelActive]}>
              {b.label}
            </Text>
            <Text style={styles.backstoryFlavor}>{b.flavor}</Text>
            {/* What the pick DOES (#390) — read from the same declaration as
                the lever it describes, never written here, so a retune of the
                modifier and the sentence describing it move together. */}
            <Text style={styles.backstoryEffect} testID={`backstory-effect-${b.id}`}>
              {b.effect}
            </Text>
          </TouchableOpacity>
        );
      })}

      {error ? <Text style={styles.error}>{error}</Text> : null}

      <TouchableOpacity style={styles.confirmButton} onPress={handleConfirm}>
        <Text style={styles.confirmText}>Begin</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 24,
    paddingBottom: 48,
    backgroundColor: colors.base,
    flexGrow: 1,
  },
  heading: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 16,
  },
  nameInput: {
    backgroundColor: colors.surfaceRaised,
    color: colors.textPrimary,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  subheading: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  backstoryCard: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: colors.border,
  },
  backstoryCardActive: {
    borderColor: colors.primary,
  },
  backstoryLabel: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 6,
  },
  backstoryLabelActive: {
    color: colors.primary,
  },
  backstoryFlavor: {
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 20,
  },
  // The mechanical statement sits under the flavor and reads brighter than it:
  // the flavor is who you were, this is what it costs or buys you.
  backstoryEffect: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    marginTop: 8,
  },
  error: {
    color: colors.danger,
    marginTop: 8,
    marginBottom: 8,
    fontSize: 14,
  },
  confirmButton: {
    marginTop: 24,
    backgroundColor: colors.primary,
    borderRadius: 10,
    padding: 16,
    alignItems: 'center',
  },
  confirmText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.base,
  },
});
